### PR TITLE
Fix title flicker

### LINKED ISSUE #36: Site title "flicker" between load and Helmet render
Need to add a default site title via a new web/config/webpack.config.js

See: https://redwoodjs.com/docs/webpack-configuration.html#configuring-webpack

```js
module.exports = (config, { _env }) => {
  config.plugins.forEach((plugin) => {
    if (plugin.constructor.name === 'HtmlWebpackPlugin') {
      plugin.options.title = 'RedwoodJS Auth Playground'
    }
  })

  return config
}
```

Right now when the site loads, the "repo" default title appears for a split second.

Also, could add "prerender" to the main route.

See: https://redwoodjs.com/docs/prerender.html#prerendering-a-page

This should hydrate the title as well.

### PR DESCRIPTION
**Pull request by morganmspencer**
Added prerender and webpack config as suggested

Closes #36

### CODE REVIEW

**Comment by dthyresson** [comment]
Thanks @morganmspencer ! LGTM. Approved and merging.

**Comment by Tobbe** [comment]
I'm confused. What happened to prerender?

**Comment by morganmspencer** [comment]
> I'm confused. What happened to prerender?

I believe the `lib/provider.js` file was not allowing prerender because the provider component is included so it's dynamic. And that file is used to create the logo cloud on the home page.

Screen Shot 2021-04-18 at 11 21 41 AM

**Comment by Tobbe** [comment]
Got it, thanks :)

**Pull request merged**
