### PR TITLE
Support Azure AD authentication: Example

### PR DESCRIPTION
**Pull request by jeliasson**
This PR seeks to make an authentication example using Azure AD.

See https://github.com/redwoodjs/redwood/issues/1310

### CODE REVIEW

**Comment by jeliasson** [comment]
### Example
This is a example output with custom role `custom-redwood-role`.

**userMetaData**
```
{
  "accountIdentifier":"50d73f03-65e8-4e3c-9a5c-XXXXXXXXX",
  "homeAccountIdentifier":"NTBkNzNmMDMtNjVlOC00ZT[...]ZGM3ZjVjNGMz.YmMxNGFkOWY[...]",
  "userName":"johan@[...]",
  "name":"Johan Eliasson",
  "idToken":{
     "aud":"99562e9b-6eb2-455d-a5e6-605a95e559d9",
     "iss":"https://login.microsoftonline.com/bc14ad9f-53e6-442a-a062-[...]/v2.0",
     "iat":1604864792,
     "nbf":1604864792,
     "exp":1604868692,
     "aio":"AVQAq/8RAAAALy[...]L6R/04ujul9XwfC6TpFEqKS3TF7f02/x4gIkueZ8j/aeUH[...]CtxeYk4/wunpaDDy7+hJPfE=",
     "name":"Johan Eliasson",
     "nonce":"30c2156f-de2b-44ce-9874-6187922c2fab",
     "oid":"50d73f03-65e8-4e3c-9a5c-XXXXXXXXX",
     "preferred_username":"johan@[...]",
     "rh":"0.ASEAn60UvOZTKk[...]peZgWpXlWdkhAFw.",
     "roles":[
        "custom-redwood-role"
     ],
     "sub":"F2WxHHIiWEw658Or1JyGA3OvTgxUjk6bdLRX1x4kVs0",
     "tid":"bc14ad9f-53e6-442a-a062-[...]",
     "uti":"wQ55wDW4vEisdnW3nE0CAA",
     "ver":"2.0"
  },
  "idTokenClaims":{
     "aud":"99562e9b-6eb2-455d-a5e6-605a95e559d9",
     "iss":"https://login.microsoftonline.com/bc14ad9f-53e6-442a-a062-[...]/v2.0",
     "iat":1604864792,
     "nbf":1604864792,
     "exp":1604868692,
     "aio":"AVQAq/8RAAAALy[...]L6R/04ujul9XwfC6TpFEqKS3TF7f02/x4gIkueZ8j/aeUH[...]CtxeYk4/wunpaDDy7+hJPfE=",
     "name":"Johan Eliasson",
     "nonce":"30c2156f-de2b-44ce-9874-6187922c2fab",
     "oid":"50d73f03-65e8-4e3c-9a5c-XXXXXXXXX",
     "preferred_username":"johan@[...]",
     "rh":"0.ASEAn60UvOZTKk[...]peZgWpXlWdkhAFw.",
     "roles":[
        "custom-redwood-role"
     ],
     "sub":"F2WxHHIiWEw658Or1JyGA3OvTgxUj[...]",
     "tid":"bc14ad9f-53e6-442a-a062-[...]",
     "uti":"wQ55wDW4vEisdnW3nE0CAA",
     "ver":"2.0"
  },
  "environment":"https://login.microsoftonline.com/bc14ad9f-53e6-442a-a062-[...]/v2.0"
}
```

**currentUser**
```
{
   "email":"johan@[...]",
   "aud":"99562e9b-6eb2-455d-a5e6-605a95e559d9",
   "iss":"https://login.microsoftonline.com/bc14ad9f-53e6-442a-a062-[...]/v2.0",
   "iat":1604864792,
   "nbf":1604864792,
   "exp":1604868692,
   "aio":"AVQAq/8RAAAALy[...]L6R/04ujul9XwfC6TpFEqKS3TF7f02/x4gIkueZ8j/aeUH[...]CtxeYk4/wunpaDDy7+hJPfE=",
   "name":"Johan Eliasson",
   "nonce":"30c2156f-de2b-44ce-9874-6187922c2fab",
   "oid":"50d73f03-65e8-4e3c-9a5c-XXXXXXXXX",
   "preferred_username":"johan@[...]",
   "rh":"0.ASEAn60UvOZTKk[...]peZgWpXlWdkhAFw.",
   "roles":[
     "custom-redwood-role"
   ],
   "sub":"F2WxHHIiWEw658Or1JyGA3OvTgxUjk6bdLRX1x4kVs0",
   "tid":"bc14ad9f-53e6-442a-a062-[...]",
   "uti":"wQ55wDW4vEisdnW3nE0CAA",
   "ver":"2.0"
}
```

**Comment by cannikin** [comment]
@thedavidprice I'm getting the "Something went wrong" page when I try to view the deploy preview for this PR...

**Comment by jeliasson** [comment]
@cannikin The developer console tells us that `azureActiveDirectory` is not supported, and I'm pretty sure this is because [https://github.com/redwoodjs/redwood/pull/1311](https://github.com/redwoodjs/redwood/pull/1311) is not merged 😊

image

You guys want me to mark this PR as a draft while the above PR is being reviewed?

**Comment by thedavidprice** [comment]
## Netlify Env Vars
Confirming that @jeliasson and I have added the necessary Env Vars to this Netlify Site.

**Comment by jeliasson** [comment]
@dthyresson @Tobbe 
At your convenience, could you please give this PR a review. I suggest a local test (i.e. clone [jeliasson/redwood](https://github.com/jeliasson/playground-auth) and checkout `feat/auth-azure-ad`), as we might want some more env's added as below to have the preview working. 

Envs can be found in `.env.defaults` and you can use test user `playground-auth-test-user1@redwoodjs.onmicrosoft.com` with password `FdoG5YZesW2Daj`. The response should obtain the custom role `plaground-auth-custom-role-1`.

Feel free to DM on Discord for any discussion or issues!

@thedavidprice 
Is it possible to add env's to a specific PR build? If so, it would be great if we could throw these in. (no stress!)

```env
AZURE_ACTIVE_DIRECTORY_REDIRECT_URI="https://deploy-preview-6--redwood-playground-auth.netlify.app"
AZURE_ACTIVE_DIRECTORY_LOGOUT_REDIRECT_URI="https://deploy-preview-6--redwood-playground-auth.netlify.app"
```

We might want to replace these once this PR is merged. (production link)
```env
AZURE_ACTIVE_DIRECTORY_REDIRECT_URI="https://redwood-playground-auth.netlify.app"
AZURE_ACTIVE_DIRECTORY_LOGOUT_REDIRECT_URI="https://redwood-playground-auth.netlify.app"
```

Thanks everyone! 🎉

**Comment by jeliasson** [comment]
@dthyresson @Tobbe 
I have bumped to version `0.22.1`. Can this be merged?

Also, I can throw in a `SUPABASE_JWT_SECRET` as per upgrade notes. Do we have this? 😀

**Comment by dthyresson** [comment]
> Also, I can throw in a `SUPABASE_JWT_SECRET` as per [upgrade notes](https://github.com/redwoodjs/redwood/releases/tag/v0.22.1). Do we have this?

@jeliasson Actually, @Tobbe and I just added and merged that into 22.1 here: https://github.com/redwoodjs/redwoodjs.com/pull/504

Thanks for thinking of this!

**Comment by jeliasson** [comment]
@dthyresson So we don't need to throw in `SUPABASE_JWT_SECRET` into this repo? If not, I think we can have this PR merged. 🎉

**Comment by dthyresson** [comment]
> @dthyresson So we don't need to throw in `SUPABASE_JWT_SECRET` into this repo? If not, I think we can have this PR merged. 🎉

My apologies @jeliasson I thought you mean adding the var to the docs, but now I see that

https://github.com/redwoodjs/playground-auth/blob/0217b31eda887251b3f3f808bf6d0457e47c7ed2/web/src/components/Supabase/Supabase.js#L7

needs to be updated.

Perhaps this is best made a separate PR:

* add the SUPABASE_JWT_SECRET
* add this to Netlify deploy environment

**Comment by dthyresson** [comment]
Actually, we have 

https://github.com/redwoodjs/playground-auth/issues/11

to handle that, so I'll close and merge!

**Pull request merged**
