### PR TITLE
Upgrading project to RedwoodJS 0.20.0

### LINKED ISSUE #8: Upgrade RedwoodJS to 0.20.0
This issue seeks to upgrade this project to RedwoodJS 0.20.0

See #9

### PR DESCRIPTION
**Pull request by jeliasson**
Closes #8

### CODE REVIEW

**Comment by thedavidprice** [comment]
Thanks for this @jeliasson It's looking good.

One final upgrade decision:
- Should this project continue using `"netlify-plugin-prisma-provider": "^0.3.0"` (in package.json)
...or...
-  switch to use `provider = ["sqlite", "postgresql"]` in `schema.prisma`

Lastly, if this is on v0.19.3, it most likey will _not_ deploy due to Prisma v2.8 build time bug with Node v12.19.0. To resolve, will need to change `.nvmrc` file to be `v12.18.4`. If Redwood v0.20.0 is out by the time this is complete, there will be a different change required but the bug with Node.js will be resolved due to upgrade to Prisma v2.9

**Comment by jeliasson** [comment]
Hey @thedavidprice 

Is 0.20.0 around the corner? As this project don't rely on database at all, it might just make sense to remove that dependency all together. Not sure why this hasn't been done as of 0.16.0 upgrade.

I'll be happy to create a new PR to align with 0.20.0 once that is out of the door. 

In the meantime, let me know what you guys want to do with this PR (besides the .nvmrc addition). ✌🏻

**Comment by peterp** [comment]
I think it's also OK to leave the database stuff in - it's not causing any problems. The connection to the DB is lazy. There may be some stage that we would want to include some sort of database persistence to the demo.

**Comment by jeliasson** [comment]
@thedavidprice @peterp 
I made a few changes that favors removal of the `netlify-plugin-prisma-provider` dependency. Please have a look at your convenience. Once `0.20.0` is out of the door, I'll make sure to make necessary changes to align this project with that version in a new PR (including changing back `.nvmrc` to `lts/*` if Prisma upgrade will fix this).

If you think it makes more sense to ditch this PR/issue in favor of a new `0.16.0`? -> `0.20.0` upgrade, do not hesitate to do so. 😊

**Comment by thedavidprice** [comment]
> I made a few changes that favors removal of the netlify-plugin-prisma-provider dependency. 

^^ got it and looks good!

'v0.20.0` has been released. I vote you go ahead and try to upgrade within this PR as the code mods should build on each other. And you might learn some helpful things to share about the upgrade process specific to v0.20. 

Want to give it a go? (And, if so, do revert `.nvmrc` back to lts.)

https://community.redwoodjs.com/t/redwoodjs-v0-20-0/1346

**Comment by jeliasson** [comment]
> Want to give it a go? [...]

On it!

**Comment by jeliasson** [comment]
@thedavidprice 
The upgrade process to `0.20.0` was smooth as silk for this repo, and mostly because there are no scaffolded components in this project.  However, I'm not sure why the [preview deploy fails](https://app.netlify.com/sites/redwood-playground-auth/deploys/5f94587f2dc62800088d7fd6). You know what's going on?

```
[...]
6:41:57 PM: Build script success
6:41:57 PM: Starting to deploy site from 'web/dist'
6:41:58 PM: Creating deploy tree 
6:41:58 PM: Creating deploy upload records
6:41:58 PM: 11 new files to upload
6:41:58 PM: 1 new functions to upload
6:42:02 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
6:43:37 PM: Failed to upload file: graphql
6:43:37 PM: Failing build: Failed to deploy site
6:44:07 PM: Failed to inform the API about a failed build, please retry the build or contact support
6:44:07 PM: Finished processing build request in 5m41.480006719s
```

I ran a local build, and the `dist/` directory in `api` weigh about 8 KB and the `web` about 4.2 MB.

**Comment by thedavidprice** [comment]
**Re: Deploy Failure**
Looks like a very strange error about the size of the GraphQL.js file
```
10:24:05 PM: Request must be smaller than 69905067 bytes for the CreateFunction operation
10:25:47 PM: Failed to upload file: graphql
10:25:47 PM: Failing build: Failed to deploy site
```

[I did a local build + zip it an ship it](https://redwoodjs.com/docs/builds.html#steps-on-netlify) --> `zipballs/` is indeed 57mb. 😬

Doing a bit more diggin now.

**Comment by thedavidprice** [comment]
@peterp Could use some help here as I'm not sure what's abnormal. Looking locally in `api/zipballs/graphql/src/node_modules` I’m seeing this packages come in at hefty sizes:
- `.prisma/client` 47mb: including engines for both Darwin (19mb) and Rhel (27mb)
- `@babel` 46mb
- `@graphql-tools` 22mb

For my tutorial test project, I end up with the same size for the Prisma engines, however:
- `@babel` 10mb
- `@graphql-tools` 10mb

**Comment by peterp** [comment]
Oh that's weird, babel shouldn't be included :/ Maybe we've introduced some kind of build bug. 🤔 We should add this to the list of things we need to test.

**Comment by thedavidprice** [comment]
@peterp I tested v0.20 deploy on both Netlify and Vercel prior to release (and again afterward when I upgraded my test project). 

Agreed about automation. One step that feels super accessible is adding a build-size check to the CI. Next.js does this for (way too many) build related metrics.

**Comment by thedavidprice** [comment]
I just ran a test build locally on a similar v0.19.3 project --> **the build size is about half**:
- it _does_ include `node_modules/@babel`
- it includes only _one_ Prisma engine for Darwin (again, this is on my local machine, I'm not sure how Netlify handles building Prisma in case of two binaryTargets

**Comment by thedavidprice** [comment]
@peterp 

Wow, I performed a `git clean` and then deleted `yarn.lock`, then re-ran the build and zip-ship process.

==> **reduced** build from 57mb to 39.1mb 🤯

Unpacked directories in `node_modules` for comparison to my original comment:
- .prisma/client 47mb (identical: including engines for both Darwin, 19mb, and Rhel,27mb)
- **@babel 5.4mb** ( _down_ from 46mb) 🎉
- @graphql-tools 17.6 (_down_ from 22mb)

wtf babel?!?

**Comment by thedavidprice** [comment]
And....

Deployed 🚀

**Comment by thedavidprice** [comment]
@jeliasson Peter and I will do further diagnosing. Otherwise, is this PR ready to merge? The code looks good to me.

**Comment by jeliasson** [comment]
@thedavidprice Yes, ready on your go. Thanks, and let me know if there is something I can help with!

/cc @peterp

**Comment by thedavidprice** [comment]
@jeliasson thanks, and will do!

@peterp the last step here seems to be testing the Auth providers. I'll hand that off to you — just let me know otherwise.

**Comment by peterp** [comment]
@thedavidprice I think if you just click on the sign in, sign out, etc and they all work then this is good to go!

**Comment by thedavidprice** [comment]
@peterp looks like things are working. 
- MagicLink accepts the emails and seems to give the appropriate console error due to invalid domain (no email hit my inbox).
- Firebase does nothing on click but yields console error about "unauthorized domain"

My assumption is that this is as good as we can get for a Preview. I'll merge now and test again -- will revert if performance changes at that time (against baseline of current version).

**Comment by thedavidprice** [comment]
### Tested the deploy

things are all working well.

MagicLink had funky behavior. First attempt was throwing errors. Then seemed to trigger and process ran correctly. ¯\_(ツ)_/¯

**Pull request merged**
