### PR TITLE
Individual pages for providers and update UI

### LINKED ISSUE #29: UI: Improve UX by adding Tabs per Provider
From @morganmspencer:

> My thought for future improvements is to allow users to tab through the different providers so only one would be on screen at a time. This could be beneficial as the list of providers grows. 

Now that this app has Tailwind by default, let's add this structure.

Let's use https://headlessui.dev/ for the TW react components when possible.

I have access to [TailwindUI components](https://tailwindui.com), so if there is a particular screen or component there that you need the code to do, let me know.

### PR DESCRIPTION
**Pull request by morganmspencer**
# Overview

This could be merged after testing, but I would love to have anyone make any potential tweaks and modifications. I want to hear from a few people to make sure they think this works.

- Uses TailwindUI logo cloud for homepage to select provider, adds logos
- Separates each provider to individual page
- Creates a provider lib file that streamlines adding new providers
- Switches providers with select box on provider page
- Creates badge component using TailwindUI badge to show if authenticated or not
- Adds Redwood logo that links to app's home page
- Uses TailwindUI form layout as wrapper for the providers
- Adds general styles to reduce the need to style every component, includes adding Redwood red color
- Adds HeadlessUI and Heroicons

Closes #29

## Notes

I went with a select box instead of tabs because my thought was if there are tons of providers in the future the tabs might get too cluttered. I originally tried the [HeadlessUI Listbox](https://headlessui.dev/react/listbox) component but it seemed easier to do a standard select box because it switches the page.

The redirect URIs would need to be updated for the providers, but it would stay consistent going forward as each provider has its own page.

I cleaned up some of the code to make it easier to add providers. Ideally, there should only need to be minimal Tailwind styles for providers as the new styles in index.css should have it covered.

I added Ethereum and Nhost, but I know we don't have those examples yet. It shows an "Example coming soon!" message instead of the provider and links to the Redwood auth docs (see screenshot). We could remove this, but I thought it might be nice to let people know even if we don't have an example.

### Home page

image

### Provider page

image

### Successful Auth

image

### Coming soon

image

### CODE REVIEW

**Comment by morganmspencer** [comment]
The workflow with this layout for future providers would be:

- Create a provider component
- Add provider logo to `src/lib/images`
- Add provider name, slug, photo, and component to `arc/lib/providers`

That's it, everything else should work as expected!

**Comment by Tobbe** [comment]
I've only looked at the screenshots so far, but visually this looks great Morgan! Only thing I'd change/add is to add a callout for help with adding the missing provider example. So instead of just saying "coming soon", I'd add something about help wanted or PRs welcome or something like that. Or "here's how to help add this" and then a link to our contributor guidelines.

**Comment by dthyresson** [comment]
@morganmspencer This is wonderful!

I turned on the Deploy Previews (as they had to be approved since you have not issued a PR before) so you should be able to see this site live now in a Netlify preview.

Let's  (1) add @Tobbe's suggestion and then (2) format the "polling refresh token" section similar to the way you did the userMetadata to preview the text overflowing the box:

image

and (3) add the how-to to the readme or contributing:

```
The workflow with this layout for future providers would be:

* Create a provider component
* Add provider logo to src/lib/images
* Add provider name, slug, photo, and component to src/lib/providers
```

and then I say we merge -- and we can think of some nice ways to improve the usermetadata or more social provider oauth logins etc in other issues.

Looks so good I bet we can link from Auth docs now!

**Comment by morganmspencer** [comment]
@dthyresson where is the contributing doc located? I was going to add to it, but I can't seem to find it

**Comment by dthyresson** [comment]
> I was going to add to it, but I can't seem to find it

@morganmspencer Sorry about that, I thought it was there, but it isn't. Please do add thanks!

**Comment by dthyresson** [comment]
@morganmspencer Let's also do 2 small other additions:

1) Add a site title (eventually we'll use React Helmet) via a new `web/config/webpack.config.js`

See:  https://redwoodjs.com/docs/webpack-configuration.html#configuring-webpack

```js
module.exports = (config, { _env }) => {
  config.plugins.forEach((plugin) => {
    if (plugin.constructor.name === 'HtmlWebpackPlugin') {
      plugin.options.title = 'RedwoodJS Auth Playground'
    }
  })

  return config
}
```

2 - Add a TW footer so we can link to this GitHub repo and other sites eventually

**Comment by morganmspencer** [comment]
> Add a site title (eventually we'll use React Helmet)

Did you want me to just add React Helmet? It should be fairly easy as there are only two pages

**Comment by dthyresson** [comment]
> > Add a site title (eventually we'll use React Helmet)
> 
> Did you want me to just add React Helmet? It should be fairly easy as there are only two pages

Sure! ;)

**Comment by dthyresson** [comment]
For react Helmet you may want to look into adding a Layout if there is not one and using the new Router Set to learn how it can wrap pages.

See: https://redwoodjs.com/docs/redwood-router.html#sets-of-routes

**Comment by morganmspencer** [comment]
All changes have been implemented!

**Comment by Tobbe** [comment]
That was fast! Nice!

**Comment by dthyresson** [comment]
Thanks! I am approving the PR to make a deploy preview. One moment ...

**Comment by dthyresson** [comment]
@Tobbe and @morganmspencer the Preview looks great

 https://607c38f1e786c80007d2f36e--redwood-playground-auth.netlify.app/

Once you both are happy with @Tobbe suggestions, @Tobbe please approve and merge.

This is great. Excited to share with the rest of the team today and let them know how you've made this so much better.

**Comment by morganmspencer** [comment]
@dthyresson I just resolved all of @Tobbe's suggestions

**Comment by dthyresson** [comment]
@morganmspencer I think a "home" link to get back to that most excellent list of all providers view, too, would be a nice quick add ;)

**Comment by dthyresson** [comment]
> @morganmspencer I think a "home" link to get back to that most excellent list of all providers view, too, would be a nice quick add ;)

Oh, it is the logo. Found it. Sorry.

**Review by dthyresson — APPROVED** [review]
LGreatTM. Thanks!

**Comment by morganmspencer** [comment]
@dthyresson and @Tobbe, do any of the redirect URLs need to be changed in the provider settings now that this is merged?

**Comment by dthyresson** [comment]
@dthyresson and @Tobbe, do any of the redirect URLs need to be changed in the provider settings now that this is merged?

Oh they likely do. I got too excited and merged.

Let me create a new issue as I've closed and merged.

**Pull request merged**
