### PR TITLE
Add authenticated badge indicator to homepage logo cloud

### LINKED ISSUE #35: On main view with all providers, add authenticated badge indicator
image

Since one can be logged in/authenticated to multiple providers, it might be nice to show an Authenticated status in each provider box, section. 

You might be able to reuse

https://github.com/redwoodjs/playground-auth/blob/main/web/src/components/Badge/Badge.js

but wrap it in the AuthProvider needed:

`<AuthProvider client={supabase} type="supabase">`

But that would require creating a client per box too, which is fine.

The "not logged in" or unauthenticated would be a nice call-to-action to then try to sign in/up.

### PR DESCRIPTION
**Pull request by morganmspencer**
# Overview

Adds the Authenticated/Not Authenticated badge to each provider on the homepage logo cloud. This shows the auth status of each provider.

- Requires client to be exported from the provider component and added to the data in `web/src/lib/providers.js`
- Only shows if a client is provided
- Updates CONTRIBUTING to include the client

Closes #35 

## Notes

Please test this a few times before merging to ensure proper functionality. I was not sure if exporting the individual client would work but it seems to.

## Screenshot

image

### CODE REVIEW

**Comment by dthyresson** [comment]
Pushed a deploy preview.

@morganmspencer I like it! -- but now that I see it given its position in the top right, with the wording it feels a little distracting.

What if this version of the badge didn't have the caption (just the dot or a tiny icon from https://heroicons.dev/) and if authenticated did a little "ping" action animation: https://tailwindcss.com/docs/animation#ping ?

The "unauthenticated" should maybe feel like it invites you to try it out - though not sure what that might look like.

**Comment by morganmspencer** [comment]
@dthyresson I added an authenticated ping if the user is logged in. I had it with a red dot for the others but it seemed a bit unnecessary. Happy to add it back in though if you want!

I agree that something like this works better, less in your face.

image

**Comment by dthyresson** [comment]
> I had it with a red dot for the others but it seemed a bit unnecessary. Happy to add it back in though if you want!

Nope defer to you. I thought it might be strange as well. Best to just show where you *are* logged in .... if not dot, then you know to try .... if dot then can know to logout, too.

Just tried the preview: https://607caf40bbb02300077bd4ff--redwood-playground-auth.netlify.app/

I really like it. Made me smile.

**Comment by Tobbe** [comment]
To me it's not immediately obvious what the green dot means.

Yes, the initial suggestion was more in your face, but it was also no question about what it meant. Also nice to have some text for a screen reader to read. And it made it easier to see if you're actually just not logged in to a provider, or if it's not even implemented yet.

Y'all think we can find some middle ground with something that's less distracting than the first suggestion, but also more descriptive than having just the green dot?

**Comment by morganmspencer** [comment]
@Tobbe for sure! I can work up something a bit more middle ground

**Comment by dthyresson** [comment]
I like the simplicity but agree that having the accessibility of text for the screen reader (hidden but available) is nice.

Let’s make a new issue or pr with ideas.

But if we do green and red the dots should be different for color blind people if accessibility is a consideration.

I personally just need an indicator of being signed in not all the states on the provider.

**Pull request merged**
