### PR TITLE
add codemirror into authresults & add style in ProviderPage Select

### PR DESCRIPTION
**Pull request by WizardSource**
Add codemirror into authresults.js for readability. 
Add style in ProviderPage Select Menu.

Screen Shot 2021-04-18 at 3 45 55 PM

### CODE REVIEW

**Comment by dthyresson** [comment]
Hi @WizardSource we're getting a build error in production deploys:

```terminal
5:47:08 PM: ERROR in ./src/components/AuthResults/AuthResults.js
5:47:08 PM: Module not found: Error: Can't resolve './CodemirrorCSS/codemirror.css' in '/opt/build/repo/web/src/components/AuthResults'
 @ ./src/components/AuthResults/AuthResults.js 9:0-40
5:47:08 PM:  @ ./src/components/MagicLink/MagicLink.js
```

and also a warning for purging styles:

```
5:47:08 PM: warn - Tailwind is not purging unused styles because no template paths have been provided.
5:47:08 PM: warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
5:47:08 PM: warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
5:47:08 PM: error Command failed with exit code 2.
```

**Comment by WizardSource** [comment]
Hi @dthyresson sorry about that I was experimenting with sizing and themes.  I believe I corrected the first error in  AuthResults.js by replacing the codemirror import paths with 
`
import 'codemirror/keymap/sublime';
import 'codemirror/theme/duotone-light.css';
import { Codemirror } from 'react-codemirror-ts';
import 'codemirror/mode/javascript/javascript';
import 'codemirror/addon/edit/matchbrackets';
import 'codemirror/lib/codemirror.css';`  

as for the Tailwind warning, I will look into it and get back to you ASAP once I find out what's causing it.

**Comment by dthyresson** [comment]
> as for the Tailwind warning, I will look into it and get back to you ASAP once I find out what's causing it.

I find that I have to use this config in my `web/tailwind.config.js`:

```js

module.exports = {
///...stuffs
  purge: {
    enabled: process.env.NETLIFY || process.env.NODE_ENV === 'production',
```

To enable purge.

Note: purge can purge some dynamic styles (if used ... not sure if are).

See: https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

**Comment by morganmspencer** [comment]
@dthyresson and @WizardSource I can write the Tailwind purge into my PR for #41. I've added these before and I think I actually have to make a quick edit so it doesn't purge a style that I added in #32 anyway

**Comment by dthyresson** [comment]
> @dthyresson and @WizardSource I wrote a PR #43 to purge Tailwind.

Ok, I'll look at that PR and merge accordingly (once the deploy preview test completes) and then @WizardSource you can rebase main to incorporate the changes.

**Pull request closed without merging**
